/**
 * The win token.
 *
 * ## What it is
 *
 * A short-lived JWS, signed with HMAC-SHA256 via `jose`, carrying the uid, the
 * riddle number and a unique token id. Ten minutes, bound to the uid it was issued
 * to.
 *
 * ## Three attacks, three defences
 *
 * 1. **Forgery.** The signature covers every claim. Changing the uid, the riddle
 *    number, or the expiry invalidates it.
 * 2. **Replay.** A `jti` is recorded as spent the moment it is redeemed, and a
 *    spent `jti` is refused before the riddle is even looked up. A token is
 *    single-use by construction, not by a check somebody can forget.
 * 3. **Cross-account use.** The uid in the token is compared against the verified
 *    uid of the caller. A token won by one reader is worthless to another, even if
 *    they somehow obtain it.
 *
 * The secret lives only in the edge environment. `RIDDLE_SIGNING_SECRET` is never
 * `NEXT_PUBLIC_`, and `scripts/check-no-riddle-leak.mjs` fails the build if the
 * value appears in the client bundle.
 */

import { SignJWT, jwtVerify, type JWTPayload } from "jose";

/** Ten minutes. Long enough to walk to a keyboard, short enough to be useless. */
export const TOKEN_TTL_SECONDS = 600;

export interface WinTokenClaims {
  uid: string;
  /** A persona id that has riddles. Validated against the bank on the way out. */
  philosopher: string;
  /** 1–3. */
  riddle: number;
  /** Issued-at, epoch seconds. */
  iat: number;
  /** Unique id, for single use. */
  jti: string;
  /** Expires-at, epoch seconds. */
  exp: number;
}

export type TokenFailure =
  | "bad_signature"
  | "expired"
  | "wrong_issuer"
  | "wrong_audience"
  | "malformed"
  | "uid_mismatch"
  | "already_used";

export type TokenResult =
  | { ok: true; claims: WinTokenClaims }
  | { ok: false; reason: TokenFailure };

const ISSUER = "mindinbox";
const AUDIENCE = "mindinbox:riddle";

function secretKey(secret: string): Uint8Array {
  return new TextEncoder().encode(secret);
}

/**
 * Mints a token.
 *
 * `jti` is generated by the caller so that the *redemption* route can record it as
 * spent as the same act that consumes it. A token minted without an id could not be
 * made single-use — and single-use is the property that stops a captured token from
 * being replayed for a second riddle.
 *
 * The token carries the philosopher as well as the riddle number, so the whole choice
 * is fixed at roll time. The client cannot ask for riddle 2 instead of riddle 1.
 */
export async function signWinToken(args: {
  secret: string;
  uid: string;
  philosopher: string;
  riddle: number;
  jti: string;
  now?: number;
}): Promise<string> {
  const nowSec = Math.floor((args.now ?? Date.now()) / 1000);
  return new SignJWT({ uid: args.uid, philosopher: args.philosopher, riddle: args.riddle })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuer(ISSUER)
    .setAudience(AUDIENCE)
    .setSubject(args.uid)
    .setIssuedAt(nowSec)
    .setExpirationTime(nowSec + TOKEN_TTL_SECONDS)
    .setJti(args.jti)
    .sign(secretKey(args.secret));
}

/**
 * Verifies a token and binds it to the caller.
 *
 * `algorithms: ["HS256"]` is pinned. Without it, a token presenting `alg: none` or
 * an asymmetric algorithm can be verified against the wrong key — the
 * `alg`-confusion attack, and one that turns a signing secret into a minting
 * oracle.
 *
 * `uid` is the verified caller, never anything from the request body.
 */
export async function verifyWinToken(args: {
  secret: string;
  token: string;
  uid: string;
  /** Persona ids this product actually has. A token naming any other is malformed. */
  knownPhilosophers: readonly string[];
  now?: number;
}): Promise<TokenResult> {
  let payload: JWTPayload;
  try {
    const result = await jwtVerify(args.token, secretKey(args.secret), {
      algorithms: ["HS256"],
      issuer: ISSUER,
      audience: AUDIENCE,
      ...(args.now !== undefined ? { currentDate: new Date(args.now) } : {}),
    });
    payload = result.payload;
  } catch (err) {
    // Matched on `code`, not on `name`. The class names have moved between `jose`
    // versions (`TokenExpiredError` became `JWTExpiredError`), so a name check
    // silently degraded every expiry into "bad signature". The token was still
    // refused — but the log claimed a forgery where there was only a late walker,
    // which is exactly the kind of false alarm that trains people to ignore the log.
    const code = (err as { code?: string })?.code ?? "";
    if (code === "ERR_JWT_EXPIRED") return { ok: false, reason: "expired" };
    if (code === "ERR_JWT_CLAIM_VALIDATION_FAILED") {
      return { ok: false, reason: "wrong_audience" };
    }
    // Everything else — a bad signature, an `alg: none`, a malformed token — is a
    // forgery attempt as far as the reader is concerned.
    return { ok: false, reason: "bad_signature" };
  }

  // Bound to the caller. A stolen token is only usable by the account that won it.
  if (payload.sub !== args.uid || payload.uid !== args.uid) {
    return { ok: false, reason: "uid_mismatch" };
  }

  const riddle = typeof payload.riddle === "number" ? payload.riddle : NaN;
  if (!Number.isInteger(riddle) || riddle < 1 || riddle > 3) {
    return { ok: false, reason: "malformed" };
  }

  // Validated against the caller's list, not against a hardcoded set, so adding a
  // philosopher's riddles does not require editing the token module — and so the
  // token cannot name a philosopher this product does not have.
  const philosopher = typeof payload.philosopher === "string" ? payload.philosopher : "";
  if (!args.knownPhilosophers.includes(philosopher)) {
    return { ok: false, reason: "malformed" };
  }

  if (typeof payload.jti !== "string" || payload.jti.length === 0) {
    return { ok: false, reason: "malformed" };
  }

  return {
    ok: true,
    claims: {
      uid: args.uid,
      philosopher,
      riddle,
      iat: payload.iat ?? 0,
      exp: payload.exp ?? 0,
      jti: payload.jti,
    },
  };
}

/** The `jti` a caller should record on redemption, so the token is single-use. */
export function newTokenId(): string {
  return crypto.randomUUID();
}
